site_name: Spanner v3
theme: readthedocs
repo_url: https://github.com/spanenrbot/spanner-v3-docs
edit_uri: edit/dev/docs/
site_url: https://bots.nexy7574.co.uk/spanner/v3/docs
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
